-- ============================================================
--  Portfolio database schema (PostgreSQL)
--  Executed idempotently on application startup.
--  Unquoted identifiers fold to lower-case in Postgres; Dapper
--  maps columns to properties case-insensitively, so the C#
--  PascalCase properties still bind correctly.
-- ============================================================

CREATE TABLE IF NOT EXISTS Projects (
    Id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title         VARCHAR(200)  NOT NULL,
    Summary       VARCHAR(600)  NOT NULL,
    Description   TEXT          NOT NULL DEFAULT '',
    TechStackJson TEXT          NOT NULL DEFAULT '[]',
    FeaturesJson  TEXT          NOT NULL DEFAULT '[]',
    MediaJson     TEXT          NOT NULL DEFAULT '[]',
    GithubLink    VARCHAR(500),
    LiveDemoLink  VARCHAR(500),
    SortOrder     INT           NOT NULL DEFAULT 0,
    CreatedAt     TIMESTAMPTZ   NOT NULL DEFAULT (now()),
    UpdatedAt     TIMESTAMPTZ   NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS AdminUsers (
    Id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username     VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(400) NOT NULL,
    CreatedAt    TIMESTAMPTZ  NOT NULL DEFAULT (now())
);

-- Generic content store for every editable section (profile, skills, experience,
-- education, stats, achievements, certifications). Each row is one item; its shape
-- lives in DataJson so new section types need no schema change.
CREATE TABLE IF NOT EXISTS ContentItems (
    Id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Section   VARCHAR(50)  NOT NULL,
    DataJson  TEXT         NOT NULL DEFAULT '{}',
    SortOrder INT          NOT NULL DEFAULT 0,
    CreatedAt TIMESTAMPTZ  NOT NULL DEFAULT (now()),
    UpdatedAt TIMESTAMPTZ  NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS IX_ContentItems_Section ON ContentItems (Section, SortOrder, Id);
